### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by jeremycherfas** [danito/KnownMastodon#34]
On attempting to add my account, email jcherfas@mac.com user etp@indieweb.social, I got an error

```TypeError: count(): Argument #1 ($value) must be of type Countable|array, string given in /home/jeremygrav/stream.jeremycherfas.net/IdnoPlugins/Mastodon/theCodingCompany/HttpRequest.php:132
Stack trace:
#0 /home/jeremygrav/stream.jeremycherfas.net/IdnoPlugins/Mastodon/theCodingCompany/HttpRequest.php(132): count('{"client_name":...')
#1 /home/jeremygrav/stream.jeremycherfas.net/IdnoPlugins/Mastodon/theCodingCompany/HttpRequest.php(86): theCodingCompany\HttpRequest::http_request('POST', 'https://indiewe...', Array, '{"client_name":...')
#2 /home/jeremygrav/stream.jeremycherfas.net/IdnoPlugins/Mastodon/theCodingCompany/oAuth.php(107): theCodingCompany\HttpRequest::Post('api/v1/apps', Array, Array)
#3 /home/jeremygrav/stream.jeremycherfas.net/IdnoPlugins/Mastodon/theCodingCompany/Mastodon.php(57): theCodingCompany\Mastodon->getAppConfig()
#4 /home/jeremygrav/stream.jeremycherfas.net/IdnoPlugins/Mastodon/Pages/Account.php(71): theCodingCompany\Mastodon->createApp('Jeremy Cherfas', 'https://stream....')
#5 /home/jeremygrav/stream.jeremycherfas.net/Idno/Common/Page.php(409): IdnoPlugins\Mastodon\Pages\Account->postContent()
#6 /home/jeremygrav/stream.jeremycherfas.net/vendor/idno/torophp/src/Toro.php(69): Idno\Common\Page->post()
#7 /home/jeremygrav/stream.jeremycherfas.net/index.php(62): Toro::serve(Object(Idno\Core\PageHandler))
#8 {main}```

When I try again, I see the button Save dimmed out, and the button Connect to IndieWeb.social. When I click on that button, something happens and I am returned to the same page.

I then have a Syndicate button on posts, but despite enabling it, syndication does not appear to take place.

**Comment by danito** [comment]
Thanks,
I have updated the Mastodon oAuth files from @crscheid
